site_name: jaxley
site_url: "https://mackelab.org/jaxley/"

nav:
  - Home: index.md
  - Tutorials:
    - Getting started: tutorial/01_morph_neurons.md
    - Run a network simulation: tutorial/02_small_network.md
    - Set parameters: tutorial/03_setting_parameters.md
    - Accelerate simulations: tutorial/04_jit_and_vmap.md
    - Define your own channels: tutorial/05_channel_and_synapse_models.md
    - Define groups: tutorial/06_groups.md
    - Optimization: tutorial/07_gradient_descent.md
  - Installation: install.md
  - Contributing: 
    - Guide: contribute.md
    - Code of Conduct: code_of_conduct.md
  - API Reference: 
    - Modules: reference/modules.md
    - Simulation: reference/integration.md
    - Mechansims: reference/mechanisms.md
    - Connecting Cells: reference/connection.md
    - Optimization: reference/optimize.md
    - Utils: reference/utils.md
  - FAQ: faq.md
  - Credits: credits.md

repo_name: 'jaxleyverse/jaxley'
repo_url: http://github.com/jaxleyverse/jaxley

theme:
  name: 'material'
  features:
  - content.code.copy
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: logo_white.png
  collapse_navigation: False

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - markdown_include.include:
      base_path: ../
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            heading_level: 3
          paths: [..]
  
watch:
  - ../jaxley
