site_name: jaxley
site_url: "https://mackelab.org/jaxley/"

nav:
  - Home: index.md
  - Tutorials:
    - Getting started: tutorial/01_small_network.md
    - Run a network simulation: tutorial/01_small_network.md
    - Set parameters: tutorial/02_setting_parameters.md
    - Obtain gradient and train: tutorial/03_gradient.md
    - Define groups: tutorial/04_groups.md
    - Define your own channels: tutorial/05_new_mechanisms.md
    - Use diverse channels: tutorial/06_diverse_channels.md
  - Installation: install.md
  - Contributing: 
    - Guide: contribute.md
    - Code of Conduct: code_of_conduct.md
  - API Reference: reference.md
  - FAQ: faq.md
  - Credits: credits.md

repo_name: 'mackelab/jaxley'
repo_url: http://github.com/mackelab/jaxley

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  collapse_navigation: False

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - markdown_include.include:
      base_path: ../
  - pymdowjx.arithmatex:
      generic: true
  - pymdowjx.betterem:
      smart_enable: all
  - pymdowjx.caret
  - pymdowjx.critic
  - pymdowjx.details
  - pymdowjx.emoji:
      emoji_generator: !!python/name:pymdowjx.emoji.to_svg
  - pymdowjx.inlinehilite
  - pymdowjx.magiclink
  - pymdowjx.mark
  - pymdowjx.smartsymbols
  - pymdowjx.superfences
  - pymdowjx.tasklist:
      custom_checkbox: true
  - pymdowjx.tilde


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            heading_level: 3
  
watch:
  - ../jaxley